# Generated by Django 5.1.5 on 2025-04-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.AlterModelOptions(
            name='organismoplan',
            options={'verbose_name': 'Relación Organismo - Plan', 'verbose_name_plural': 'Relación Organismo - Plan'},
        ),
        migrations.AlterModelOptions(
            name='organismosectorial',
            options={'verbose_name': 'Organismo Sectorial', 'verbose_name_plural': 'Organismos Sectoriales'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='tipomedida',
            options={'verbose_name': 'Tipo de medida', 'verbose_name_plural': 'Tipos de medidas'},
        ),
        migrations.AlterModelOptions(
            name='verificacion',
            options={'verbose_name': 'Verificación', 'verbose_name_plural': 'Verificaciones'},
        ),
        migrations.AlterModelOptions(
            name='verificacionmedida',
            options={'verbose_name': 'Relación Verificación - medida', 'verbose_name_plural': 'Relación Verificación - medida'},
        ),
        migrations.RemoveField(
            model_name='medidareportada',
            name='usuario',
        ),
    ]
